# rise up test evironment
# ansible-playbook tasks/rise.yml
# optionally you can --skip-tags=installation
# to turn it down:
# docker-compose -f files/docker-compose.yml -p multiuser down
---
- name: deploy test hosts to local
  hosts: localhost
  connection: local
  vars:
    sysadmin: user # override with -e "sysadmin=you"
  tasks:
  # INSTALLATION
    - name: ensure docker community edition is present
      apt:
        name: docker-ce
        update_cache: yes
      become: yes
      tags: installation
  
    - name: ensure python is present
      apt: name=python state=present
      tags: installation

    - name: ensure pip is present
      easy_install:
        name: pip
        state: present
      become: yes
      tags: installation

    - name: ensure python package docker is present
      pip:
        name: docker
        state: present
      become: yes
      tags: installation

    - name: ensure python package docker-compose is present
      pip:
        name: docker-compose
        state: present
      become: yes
      tags: installation
  
  # SET UP THIS EXERCISE
  
    - name: link your key as sysadmin
      file:
        src: "{{ sysadmin }}.pub"
        dest: ../files/ssh/sysadmin.pub
        state: link

    - name: pull slim linux image
      docker_image:
        name: gliderlabs/alpine:latest
        state: present

    
    - name: build the test image with ssh and bash
      docker_image:
        name: testhost
        path: ../files
        state: present
        force: yes

    - name: deploy ten hosts for this exercise
      docker_service:
        project_src: ../files/
        project_name: multiuser
      register: output

    - name: ensure hosts file exists and is empty
      copy:
        content: ""
        dest: ../hosts.test

    - name: generate a hosts file with the desired hostnames and assigned IPs of the test environment
      lineinfile:
        path: ../hosts.test
        line: "multiuser_{{ hostn }}_1  ansible_host={{ output.ansible_facts[hostn].values()[0].networks.multiuser_free.IPAddress }}"
        state: present
      with_items: "{{ output.ansible_facts }}"
      loop_control:
        loop_var: hostn
