---
users:
  
  - name: john
    comment: "Doe the famous"
    allowed:
      - all
  
  - name: joe
    comment: "Black do you know her"
    sudo: yes
    allowed:
      - multiuser_1_1
      - multiuser_2_1
  
  - name: mr
    comment: "Mr.X"
  
  - name: mrs
    comment: "Mrs. User"
    shell: yes
    allowed:
      - multiuser_2_1
      - multiuser_3_1
  
  - name: monsieur
    comment: "Mr. Francois"
    shell: no
    allowed:
      - multiuser_4_1
      - multiuser_8_1
  
  - name: madamme
    comment: "Mmme. Francesca"
    allowed:
      - multiuser_5_1
      - multiuser_6_1
      - multiuser_7_1

  - name: lgtbiq
    comment: "LGTBIQplus"
    allowed:
      - multiuser_1_1
      - multiuser_2_1

  - name: shuk
    comment: "uno"
    sudo: yes
    allowed:
      - multiuser_1_1
  
  - name: ishkay
    comment: "dos"
#    sudo: yes
    allowed:
      - multiuser_2_1
  
  - name: kimsa
    comment: "tres"
    allowed:
      - miltiuser_3_1
  
  - name: chusku
    comment: "cuatro"
    allowed:
      - multiuser_4_1
  
  - name: pichka
    comment: "cinco"
    allowed:
      - multiuser_5_1
  
  - name: sukta
    comment: "seis"
    allowed:
      - multiuser_6_1
  
  - name: kanchis
    comment: "siete"
    allowed:
      - miltiuser_7_1
  
  - name: pusak
    comment: "ocho"
    allowed:
      - multiuser_8_1

