---

- name: ensure sudo is present
  tags: apt
  apt: name=sudo state=present

- name: Make sure we have a 'sudo' group
  group: name=sudo state=present

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

