---

- name: sudo package required
  tags: apt
  apt: name=sudo state=present

- name: create 'sudo' group
  group: name=sudo state=present

- name: passwordless sudo for group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: user creation at hosts
  user:
    name: "{{ item.0.name }}"
    comment: "{{ item.0.comment }}"
    state: present
    shell: "{{ item.0.shell | default('/bin/bash') }}"
  with_subelements:
    - "{{ users }}"
    # second loop
    - allowed
    - skip_missing: true
  when: item.1 == inventory_hostname or item.1 == "all"
