---

- name: sudo package required
  apk: name=sudo state=present

- name: create 'sudo' group
  group: name=sudo state=present

- name: allow passwordless sudo for group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: user creation at hosts
  user:
    name: "{{ item.0.name }}"
    comment: "{{ item.0.comment }}"
    state: present
    password: '*'
    shell: "{% if item.0.sudo is defined and item.0.sudo is sameas true %}{{ item.0.shell | default('/bin/bash', true) }}{% elif item.0.shell is defined %}{% if item.0.shell is string %}{{ item.0.shell | default('/bin/bash') }}{% elif item.0.shell is sameas true %}/bin/bash{% endif %}{% endif %}"
  with_subelements:
    - "{{ users }}"
    - allowed
    - skip_missing: true
  when: item.1 == inventory_hostname or item.1 == "all"
  
- name: populate user ssh public keys
  authorized_key: user="{{ item.0.name }}"
                  key="{{ lookup('file', 'ssh/'+item.0.name+'.pub') }}"
                  state=present
  with_subelements:
    - "{{ users }}"
    - allowed
    - skip_missing: true
  when: item.1 == inventory_hostname or item.1 == "all"

- name: add users to sudo group
  user:
    name: "{{ item.0.name }}"
    state: present
    groups: sudo
    append: yes
  with_subelements:
    - "{{ users }}"
    - allowed
    - skip_missing: true
  when: ( item.1 == inventory_hostname or item.1 == "all" ) and (item.0.sudo|default(false))
